kind: Deployment
apiVersion: apps/v1
metadata:
  name: nie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nie
      tier: frontend
  template:
    metadata:
      labels:
        app: nie
        tier: frontend
    spec:
      containers:
      - name: nie-container
        image: waterarmy-docker.pkg.coding.net/spa/room/nie:coding-ci-7uo-1h79ren7g
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: dev
        resources:
          requests:
            cpu: 1m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
      imagePullSecrets:
      - name: coding-spa
