kind: Deployment
apiVersion: apps/v1
metadata:
  name: rou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rou
      tier: frontend
  template:
    metadata:
      labels:
        app: rou
        tier: frontend
    spec:
      containers:
      - name: rou-container
        image: waterarmy-docker.pkg.coding.net/spa/room/rou:coding-ci-1e3-1h79rb2hd
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: dev
        resources:
          requests:
            cpu: 1m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
      imagePullSecrets:
      - name: coding-spa
