kind: Deployment
apiVersion: apps/v1
metadata:
  name: tui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tui
      tier: frontend
  template:
    metadata:
      labels:
        app: tui
        tier: frontend
    spec:
      containers:
      - name: tui-container
        image: waterarmy-docker.pkg.coding.net/spa/room/tui:coding-ci-6ro-1h6t5olig
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: dev
        resources:
          requests:
            cpu: 1m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
      imagePullSecrets:
      - name: coding-spa
