kind: Deployment
apiVersion: apps/v1
metadata:
  name: xiuluo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xiuluo
      tier: frontend
  template:
    metadata:
      labels:
        app: xiuluo
        tier: frontend
    spec:
      containers:
      - name: xiuluo-container
        image: yuhenabc/xiuluo
        ports:
        - containerPort: 80
        env:
        - name: ENV
          value: dev
        resources:
          requests:
            cpu: 1m
            memory: 25Mi
          limits:
            cpu: 100m
            memory: 50Mi
